########
# 1. find person
#
GET http://localhost:8080/find/3
Content-Type: application/json

########
# 2. delete person
#
DELETE http://localhost:8080/delete/1
Content-Type: application/json

########
# 3. edit person
#
PATCH http://localhost:8080/update/1
Content-Type: application/json

{
    "name": "Anna",
    "surname": "Ivanova",
    "patronymic": "Vasilevna",
    "age": 24,
    "gender": "man",
    "nationality": "russian"
}

########
# 4. add person (fio)
#
POST http://localhost:8080/add
Content-Type: application/json

{
    "name": "Dmitriy",
    "surname": "Ushakov",
    "patronymic": "Vasilevich",
    "age": 30,
    "gender": "man",
    "nationality": "russian"
}
