services:
  postgres:
    container_name: dev_db_effmobile
    image: postgres:14.3-alpine
    ports:
      - "15438:5432"
    environment:
      POSTGRES_DB: effmobile_dev
      PGDATABASE: effmobile_dev
      POSTGRES_USER: effmobile
      PGUSER: effmobile
      POSTGRES_PASSWORD: effmobile
    volumes:
      - dev-db-effective-mobile-task:/var/lib/postgresql/data

volumes:
  dev-db-effective-mobile-task:
